version: "3.9"
services:
  
  ros2_mod1:
 
    build:
      context: ./ros_demo_module1
      dockerfile: ./ros_demo_module1/Dockerfile
    image: demo_env1:latest
    container_name: mod1
    privileged: true
    volumes:
      - ./ros_demo_module1/src:/root/ros2_ws/src
    tty: true
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID=42
    networks:
      ros_demo_network:
        ipv4_address: 172.69.0.2
    # UNCOMMENT ENTRYPOINT IF: you don't want the ROS packages launch automatically at container startup
    # entrypoint: ["tail", "-f", "/dev/null"]

  ros2_mod2:
 
    build:
      context: ./ros_demo_module2
      dockerfile: ./ros_demo_module2/Dockerfile
    image: demo_env2:latest
    container_name: mod2
    privileged: true
    volumes:
      - ./ros_demo_module2/src:/root/ros2_ws/src
    tty: true
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID=42
    networks:
      ros_demo_network:
        ipv4_address: 172.69.0.3
    # UNCOMMENT ENTRYPOINT IF: you don't want the ROS packages launch automatically at container startup
    # entrypoint: ["tail", "-f", "/dev/null"]

networks:
  ros_demo_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.69.0.0/16